# Generated by Django 5.1 on 2024-08-22 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_process', '__first__'),
        ('hash_process', '__first__'),
        ('ip_process', '__first__'),
        ('mail_feeder', '__first__'),
        ('url_process', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('analysis_done', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('To Do', 'Todo'), ('On Going', 'Ongoing'), ('Challenged', 'Challenged'), ('Done', 'Done')], default='To Do', max_length=20, verbose_name='Status')),
                ('results', models.CharField(choices=[('Safe', 'Safe'), ('Inconclusive', 'Inconclusive'), ('Unchallenged', 'Unchallenged'), ('Whitelisted', 'Whitelisted'), ('Failure', 'Failure'), ('Suspicious', 'Suspicious'), ('Dangerous', 'Dangerous')], default='Inconclusive', max_length=20, verbose_name='Results')),
                ('finalScore', models.FloatField(default=0)),
                ('finalConfidence', models.FloatField(default=0)),
                ('is_challenged', models.BooleanField(default=False)),
                ('challenged_result', models.CharField(choices=[('Safe', 'Safe'), ('Inconclusive', 'Inconclusive'), ('Unchallenged', 'Unchallenged'), ('Whitelisted', 'Whitelisted'), ('Failure', 'Failure'), ('Suspicious', 'Suspicious'), ('Dangerous', 'Dangerous')], default='Unchallenged', max_length=20, verbose_name='Challenged Result')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_last_update_by', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseHasFileOrMail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_has_file_or_mail', to='case_handler.case')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_has_file_or_mail', to='file_process.file')),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_has_file_or_mail', to='mail_feeder.mail')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='fileOrMail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='case_handler.casehasfileormail'),
        ),
        migrations.CreateModel(
            name='CaseHasNonFileIocs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_has_non_file_iocs', to='case_handler.case')),
                ('hash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_has_non_file_iocs', to='hash_process.hash')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_has_non_file_iocs', to='ip_process.ip')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_has_non_file_iocs', to='url_process.url')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='nonFileIocs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='case_handler.casehasnonfileiocs'),
        ),
        migrations.CreateModel(
            name='FileInCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('case', models.ManyToManyField(to='case_handler.case')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_cases', to='file_process.file')),
            ],
        ),
        migrations.CreateModel(
            name='HashInCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('case', models.ManyToManyField(to='case_handler.case')),
                ('hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_cases', to='hash_process.hash')),
            ],
        ),
        migrations.CreateModel(
            name='IpInCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('case', models.ManyToManyField(to='case_handler.case')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_cases', to='ip_process.ip')),
            ],
        ),
        migrations.CreateModel(
            name='MailInCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('associated_cases', models.ManyToManyField(to='case_handler.case')),
                ('associated_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_associated_with_mail', to='mail_feeder.mail')),
            ],
        ),
        migrations.CreateModel(
            name='UrlInCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('case', models.ManyToManyField(to='case_handler.case')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_cases', to='url_process.url')),
            ],
        ),
    ]
