# Generated by Django 5.1.7 on 2025-03-17 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='casehasfileormail',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='casehasnonfileiocs',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='fileincases',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='hashincases',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='ipincases',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='mailincases',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='urlincases',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='case',
            name='challenged_result',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Inconclusive', 'Inconclusive'), ('Unchallenged', 'Unchallenged'), ('Whitelisted', 'Whitelisted'), ('Failure', 'Failure'), ('Suspicious', 'Suspicious'), ('Dangerous', 'Dangerous')], db_index=True, default='Unchallenged', max_length=20, verbose_name='Challenged Result'),
        ),
        migrations.AlterField(
            model_name='case',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='finalConfidence',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='finalScore',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='case',
            name='results',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Inconclusive', 'Inconclusive'), ('Unchallenged', 'Unchallenged'), ('Whitelisted', 'Whitelisted'), ('Failure', 'Failure'), ('Suspicious', 'Suspicious'), ('Dangerous', 'Dangerous')], db_index=True, default='Inconclusive', max_length=20, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('On Going', 'On Going'), ('Challenged', 'Challenged'), ('Done', 'Done')], db_index=True, default='To Do', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='casehasfileormail',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='casehasfileormail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='casehasnonfileiocs',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='casehasnonfileiocs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fileincases',
            name='case',
            field=models.ManyToManyField(blank=True, related_name='file_cases', to='case_handler.case'),
        ),
        migrations.AlterField(
            model_name='fileincases',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fileincases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hashincases',
            name='case',
            field=models.ManyToManyField(blank=True, related_name='hash_cases', to='case_handler.case'),
        ),
        migrations.AlterField(
            model_name='hashincases',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hashincases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipincases',
            name='case',
            field=models.ManyToManyField(blank=True, related_name='ip_cases', to='case_handler.case'),
        ),
        migrations.AlterField(
            model_name='ipincases',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ipincases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailincases',
            name='associated_cases',
            field=models.ManyToManyField(blank=True, related_name='mail_cases', to='case_handler.case'),
        ),
        migrations.AlterField(
            model_name='mailincases',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailincases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='urlincases',
            name='case',
            field=models.ManyToManyField(blank=True, related_name='url_cases', to='case_handler.case'),
        ),
        migrations.AlterField(
            model_name='urlincases',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='urlincases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='case_handle_status_649cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['results'], name='case_handle_results_536235_idx'),
        ),
    ]
