# Generated by Django 5.1.7 on 2025-04-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0002_alter_case_options_alter_casehasfileormail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='categoryAI',
            field=models.CharField(db_index=True, default='Uncategorized', max_length=20, verbose_name='Category AI'),
        ),
        migrations.AddField(
            model_name='case',
            name='confidenceIA',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='resultsIA',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Inconclusive', 'Inconclusive'), ('Unchallenged', 'Unchallenged'), ('Whitelisted', 'Whitelisted'), ('Failure', 'Failure'), ('Suspicious', 'Suspicious'), ('Dangerous', 'Dangerous')], db_index=True, default='Suspicious', max_length=20, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='case',
            name='scoreIA',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='results',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Inconclusive', 'Inconclusive'), ('Unchallenged', 'Unchallenged'), ('Whitelisted', 'Whitelisted'), ('Failure', 'Failure'), ('Suspicious', 'Suspicious'), ('Dangerous', 'Dangerous')], db_index=True, default='Suspicious', max_length=20, verbose_name='Results'),
        ),
    ]
