# Generated by Django 5.2 on 2025-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0003_case_categoryai_case_confidenceia_case_resultsia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='confidenceIA',
            new_name='confidenceAI',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='scoreIA',
            new_name='scoreAI',
        ),
        migrations.RemoveField(
            model_name='case',
            name='resultsIA',
        ),
        migrations.AddField(
            model_name='case',
            name='resultsAI',
            field=models.CharField(db_index=True, default='Suspicious', max_length=20, verbose_name='ResultsAI'),
        ),
    ]
