# Generated by Django 5.2.3 on 2025-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0004_rename_confidenceia_case_confidenceai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='confidence',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
