# Generated by Django 5.2.10 on 2026-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0007_casechallengetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_challengeable',
            field=models.BooleanField(default=True),
        ),
    ]
