# Generated by Django 6.0.4 on 2026-05-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0009_rename_case_camelcase_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='case',
            name='case_handle_status_649cb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='case_handle_results_536235_idx',
        ),
    ]
