# Generated by Django 6.0.4 on 2026-05-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0012_consolidate_case_artifacts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caseartifact',
            name='caseartifact_unique_file',
        ),
        migrations.RemoveConstraint(
            model_name='caseartifact',
            name='caseartifact_unique_hash',
        ),
        migrations.RemoveConstraint(
            model_name='caseartifact',
            name='caseartifact_unique_url',
        ),
        migrations.RemoveConstraint(
            model_name='caseartifact',
            name='caseartifact_unique_ip',
        ),
        migrations.RemoveConstraint(
            model_name='caseartifact',
            name='caseartifact_unique_mail',
        ),
    ]
