# Generated by Django 6.0.5 on 2026-07-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0013_drop_caseartifact_partial_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalized At'),
        ),
        migrations.AddField(
            model_name='case',
            name='lifecycle_state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ANALYZING', 'Analyzing'), ('SCORING', 'Scoring'), ('FINALIZED', 'Finalized'), ('CONTESTED', 'Contested')], db_index=True, default='CREATED', max_length=20, verbose_name='Lifecycle State'),
        ),
    ]
