# Generated by Django 6.0.5 on 2026-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0015_backfill_lifecycle_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dispatched At'),
        ),
    ]
