# Generated by Django 6.0.5 on 2026-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0016_case_dispatched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='kpi_counted',
            field=models.BooleanField(default=False, verbose_name='KPI Counted'),
        ),
    ]
