# Generated by Django 6.0.5 on 2026-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0019_case_challenge_proposed_result_case_challenge_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reporter_context',
            field=models.TextField(blank=True, default='', verbose_name='Reporter Context'),
        ),
    ]
