# Generated by Django 6.0.5 on 2026-07-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0021_casecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='thehive_alert_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='TheHive Alert ID'),
        ),
    ]
