# Generated by Django 6.0.7 on 2026-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0023_backfill_confidence_ai_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_allowlisted',
            field=models.BooleanField(default=False, verbose_name='Is Allowlisted'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_denylisted',
            field=models.BooleanField(default=False, verbose_name='Is Denylisted'),
        ),
        migrations.AddField(
            model_name='case',
            name='list_reason',
            field=models.TextField(blank=True, default='', verbose_name='Allow/Deny List Reason'),
        ),
    ]
