# Generated by Django 6.0.7 on 2026-09-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0024_case_is_allowlisted_case_is_denylisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='inconclusive_reason',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='verdict_rationale',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
