# Generated by Django 6.0.7 on 2026-09-03 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0025_case_verdict_metadata'),
        ('domain_process', '0002_domain_ioc_confidence_domain_ioc_level_and_more'),
        ('hash_process', '0002_alter_hash_ioc_level_alter_hash_ioc_score'),
        ('ip_process', '0003_alter_ip_address_ipv6'),
        ('url_process', '0004_url_analysis_status_url_analyzed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ObservableGroupArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('URL', 'URL'), ('IP', 'IP'), ('HASH', 'Hash'), ('DOMAIN', 'Domain')], db_index=True, max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable_group_artifacts', to='domain_process.domain')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='case_handler.observablegroup')),
                ('hash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable_group_artifacts', to='hash_process.hash')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable_group_artifacts', to='ip_process.ip')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable_group_artifacts', to='url_process.url')),
            ],
            options={
                'ordering': ['creation_date'],
                'indexes': [models.Index(fields=['group', 'artifact_type'], name='case_handle_group_i_1edfff_idx')],
            },
        ),
    ]
