# Generated by Django 6.0.7 on 2026-09-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0026_observable_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='observable_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='case_handler.observablegroup'),
        ),
    ]
