# Generated by Django 6.1 on 2026-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0027_case_observable_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='verdict_explanation',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
