# Generated by Django 6.1.1 on 2026-10-07 08:52

import case_handler.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0028_case_verdict_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default=case_handler.models._new_campaign_ref, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_refs', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.JSONField(blank=True, default=list)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='case_handler.campaign')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_membership', to='case_handler.case')),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
    ]
