# Generated by Django 6.1.1 on 2026-10-07 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0029_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-creation_date'], name='case_status_created_idx'),
        ),
    ]
