# Generated by Django 6.1.1 on 2026-10-08 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0030_lookup_indexes'),
        ('domain_process', '0003_domain_value_prefix_index'),
        ('file_process', '0002_alter_file_file_level_alter_file_file_score'),
        ('hash_process', '0003_lookup_indexes'),
        ('ip_process', '0004_lookup_indexes'),
        ('mail_feeder', '0022_delete_mailanalyzed'),
        ('url_process', '0005_url_address_prefix_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('observable_group__isnull', True), models.Q(('fileOrMail__isnull', True), ('nonFileIocs__isnull', True)), _connector='OR'), name='case_group_excludes_other_roads_chk'),
        ),
        migrations.AddConstraint(
            model_name='caseartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('hash__isnull', True), ('url__isnull', True), ('ip__isnull', True), ('mail__isnull', True)), models.Q(('hash__isnull', False), ('file__isnull', True), ('url__isnull', True), ('ip__isnull', True), ('mail__isnull', True)), models.Q(('url__isnull', False), ('file__isnull', True), ('hash__isnull', True), ('ip__isnull', True), ('mail__isnull', True)), models.Q(('ip__isnull', False), ('file__isnull', True), ('hash__isnull', True), ('url__isnull', True), ('mail__isnull', True)), models.Q(('mail__isnull', False), ('file__isnull', True), ('hash__isnull', True), ('url__isnull', True), ('ip__isnull', True)), _connector='OR'), name='caseartifact_one_target_chk'),
        ),
        migrations.AddConstraint(
            model_name='casehasfileormail',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('mail__isnull', True)), models.Q(('mail__isnull', False), ('file__isnull', True)), _connector='OR'), name='casehasfileormail_one_target_chk'),
        ),
        migrations.AddConstraint(
            model_name='casehasnonfileiocs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('url__isnull', False), ('ip__isnull', True), ('hash__isnull', True)), models.Q(('ip__isnull', False), ('url__isnull', True), ('hash__isnull', True)), models.Q(('hash__isnull', False), ('url__isnull', True), ('ip__isnull', True)), _connector='OR'), name='casehasnonfileiocs_one_target_chk'),
        ),
        migrations.AddConstraint(
            model_name='observablegroupartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('url__isnull', False), ('ip__isnull', True), ('hash__isnull', True), ('domain__isnull', True)), models.Q(('ip__isnull', False), ('url__isnull', True), ('hash__isnull', True), ('domain__isnull', True)), models.Q(('hash__isnull', False), ('url__isnull', True), ('ip__isnull', True), ('domain__isnull', True)), models.Q(('domain__isnull', False), ('url__isnull', True), ('ip__isnull', True), ('hash__isnull', True)), _connector='OR'), name='observablegroupartifact_one_target_chk'),
        ),
    ]
