# Generated by Django 5.1.6 on 2025-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='fragment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='url',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='url',
            name='ports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='query',
            field=models.TextField(default=''),
        ),
    ]
