# Generated by Django 5.1.6 on 2025-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_process', '0002_url_fragment_url_path_url_ports_url_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='ioc_level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='url',
            name='ioc_score',
            field=models.FloatField(default=5),
        ),
    ]
