# Generated by Django 6.0.5 on 2026-06-23 08:17

import django.db.models.deletion
from django.db import migrations, models


def _backfill_canonical_key(apps, schema_editor):
    from url_process.url_utils.url_planner import canonical_key
    URL = apps.get_model("url_process", "URL")
    batch = []
    for row in URL.objects.all().only("id", "address").iterator():
        try:
            key = canonical_key(row.address or "")
        except Exception:
            key = ""
        if key:
            row.canonical_key = key
            batch.append(row)
        if len(batch) >= 500:
            URL.objects.bulk_update(batch, ["canonical_key"])
            batch = []
    if batch:
        URL.objects.bulk_update(batch, ["canonical_key"])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('url_process', '0003_alter_url_ioc_level_alter_url_ioc_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('reused', 'Reused'), ('skipped', 'Skipped')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='url',
            name='analyzed_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reused_by', to='url_process.url'),
        ),
        migrations.AddField(
            model_name='url',
            name='canonical_key',
            field=models.CharField(db_index=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='url',
            name='interestingness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(_backfill_canonical_key, _noop_reverse),
    ]
