# Generated by Django 6.0.4 on 2026-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('last_health_ok', models.BooleanField(blank=True, null=True)),
                ('last_health_detail', models.TextField(blank=True, default='')),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=50)),
                ('case_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('skipped', 'skipped')], max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['connector', '-created_at'], name='connectors__connect_ea2ab9_idx'), models.Index(fields=['case_id'], name='connectors__case_id_ad0b7c_idx')],
            },
        ),
    ]
