// Auto-generated by `boneyard-js` (Vite plugin or `npx boneyard-js build`).
// This stub is the initial empty registry; it is overwritten whenever the
// dev server boots or `boneyard-js build` runs and produces bone snapshots
// for every <Skeleton name="..."> in the codebase.
//
// Safe to commit — the regenerated file imports any .bones.json files that
// exist and calls registerBones() with their contents. Until the first
// capture runs, <Skeleton> components fall back to their `fixture` prop
// or render their children directly.
export {};
