# Generated by Django 5.1 on 2024-08-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_process', '__first__'),
        ('url_process', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('category', models.CharField(default='unknown category', max_length=50)),
                ('times_sent', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainInIocs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_iocs', to='domain_process.domain')),
                ('mail_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_iocs', to='email_process.mailaddress')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_iocs', to='url_process.url')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='linked_mail_addresses',
            field=models.ManyToManyField(related_name='domains', through='domain_process.DomainInIocs', to='email_process.mailaddress'),
        ),
        migrations.AddField(
            model_name='domain',
            name='linked_urls',
            field=models.ManyToManyField(related_name='domains', through='domain_process.DomainInIocs', to='url_process.url'),
        ),
    ]
