# Generated by Django 5.2.1 on 2025-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ioc_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='ioc_level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='ioc_score',
            field=models.FloatField(default=5),
        ),
    ]
