apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suspicious.fullname" . }}-feeder-config
  labels:
    {{- include "suspicious.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{ .Values.feederConfig | default dict | toJson }}
