apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suspicious.fullname" . }}-tls-bundle
  labels:
    {{- include "suspicious.labels" . | nindent 4 }}
type: Opaque
stringData:
  certfile.pem: {{ .Values.tlsBundle.certfile | quote }}
  keyfile.pem: {{ .Values.tlsBundle.keyfile | quote }}
  rootcafile.pem: {{ .Values.tlsBundle.rootcafile | quote }}
