# Generated by Django 5.1 on 2024-08-22 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hash_process', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='files/')),
                ('file_score', models.FloatField(default=0)),
                ('file_confidence', models.FloatField(default=0)),
                ('file_level', models.CharField(default='unknown level', max_length=20)),
                ('tmp_path', models.TextField()),
                ('filetype', models.CharField(default='unknown filetype', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('other_names', models.TextField()),
                ('times_sent', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('linked_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='hash_process.hash')),
            ],
        ),
        migrations.CreateModel(
            name='HashFromFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_files', to='file_process.file')),
                ('hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_files', to='hash_process.hash')),
            ],
        ),
    ]
