apiVersion: v1
kind: Service
metadata:
  name: {{ include "suspicious.fullname" . }}-feeder
  labels:
    {{- include "suspicious.labels" . | nindent 4 }}
    app.kubernetes.io/component: feeder
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: feeder
  ports:
    - port: {{ .Values.feeder.service.port }}
      targetPort: 9091
