services:
  traefik:
    init: true
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - suspicious
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ${TRAEFIK_PATH}/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ${TRAEFIK_PATH}/dynamic:/dynamic:ro
      - ${CA_PATH}:/etc/private:ro
      - ${TRAEFIK_PATH}/logs:/var/log/traefik


networks:
  suspicious:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

