# Generated by Django 5.1 on 2024-08-22 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain_process', '0001_initial'),
        ('email_process', '0001_initial'),
        ('file_process', '0001_initial'),
        ('hash_process', '0001_initial'),
        ('ip_process', '0001_initial'),
        ('url_process', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('reportedBy', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('to', models.CharField(max_length=255)),
                ('cc', models.CharField(blank=True, max_length=255)),
                ('mail_id', models.CharField(max_length=255)),
                ('times_sent', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailBody',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body_score', models.FloatField(default=0)),
                ('body_confidence', models.FloatField(default=0)),
                ('body_level', models.CharField(default='unknown level', max_length=20)),
                ('body_value', models.TextField()),
                ('fuzzy_hash', models.TextField()),
                ('times_sent', models.PositiveIntegerField(default=0)),
                ('other_values', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header_score', models.FloatField(default=0)),
                ('header_confidence', models.FloatField(default=0)),
                ('header_level', models.CharField(default='unknown level', max_length=20)),
                ('header_value', models.TextField()),
                ('fuzzy_hash', models.TextField()),
                ('other_values', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactIsUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_artifacts', to='url_process.url')),
                ('associated_mails', models.ManyToManyField(to='mail_feeder.mail')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactIsMailAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('mail_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_address_artifacts', to='email_process.mailaddress')),
                ('associated_mails', models.ManyToManyField(to='mail_feeder.mail')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactIsIp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_artifacts', to='ip_process.ip')),
                ('associated_mails', models.ManyToManyField(to='mail_feeder.mail')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactIsHash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_artifacts', to='hash_process.hash')),
                ('associated_mails', models.ManyToManyField(to='mail_feeder.mail')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactIsDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_artifacts', to='domain_process.domain')),
                ('associated_mails', models.ManyToManyField(to='mail_feeder.mail')),
            ],
        ),
        migrations.CreateModel(
            name='MailAnalyzed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_phishing', models.BooleanField(default=False)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('is_legitimate', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_analyzed', to='mail_feeder.mail')),
            ],
        ),
        migrations.CreateModel(
            name='MailArtifact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artifact_score', models.FloatField(default=0)),
                ('artifact_confidence', models.FloatField(default=0)),
                ('artifact_level', models.CharField(default='unknown level', max_length=20)),
                ('artifact_type', models.CharField(choices=[('URL', 'URL'), ('IP', 'IP'), ('Hash', 'Hash'), ('Domain', 'Domain'), ('MailAddress', 'MailAddress')], max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('artifactIsDomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_artifacts', to='mail_feeder.artifactisdomain')),
                ('artifactIsHash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_artifacts', to='mail_feeder.artifactishash')),
                ('artifactIsIp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_artifacts', to='mail_feeder.artifactisip')),
                ('artifactIsMailAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_artifacts', to='mail_feeder.artifactismailaddress')),
                ('artifactIsUrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_artifacts', to='mail_feeder.artifactisurl')),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_artifacts',
            field=models.ManyToManyField(to='mail_feeder.mailartifact'),
        ),
        migrations.AddField(
            model_name='artifactisurl',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_artifacts', to='mail_feeder.mailartifact'),
        ),
        migrations.AddField(
            model_name='artifactismailaddress',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_address_artifacts', to='mail_feeder.mailartifact'),
        ),
        migrations.AddField(
            model_name='artifactisip',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_artifacts', to='mail_feeder.mailartifact'),
        ),
        migrations.AddField(
            model_name='artifactishash',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_artifacts', to='mail_feeder.mailartifact'),
        ),
        migrations.AddField(
            model_name='artifactisdomain',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_artifacts', to='mail_feeder.mailartifact'),
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_score', models.FloatField(default=0)),
                ('attachment_confidence', models.FloatField(default=0)),
                ('attachment_level', models.CharField(default='unknown level', max_length=20)),
                ('att_hash_score', models.FloatField(default=0)),
                ('att_hash_confidence', models.FloatField(default=0)),
                ('att_hash_level', models.CharField(default='unknown level', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_attachments', to='file_process.file')),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_attachments',
            field=models.ManyToManyField(to='mail_feeder.mailattachment'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mail_feeder.mailbody'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mail_feeder.mailheader'),
        ),
        migrations.CreateModel(
            name='MailInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_received', models.BooleanField(default=False)),
                ('user_reception_informed', models.BooleanField(default=False)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('user_analysis_informed', models.BooleanField(default=False)),
                ('is_phishing', models.BooleanField(default=False)),
                ('user_phishing_informed', models.BooleanField(default=False)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('user_dangerous_informed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_info', to='mail_feeder.mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
