# Generated by Django 5.0.7 on 2024-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactisdomain',
            name='times_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artifactishash',
            name='times_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artifactisip',
            name='times_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artifactismailaddress',
            name='times_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artifactisurl',
            name='times_sent',
            field=models.IntegerField(default=0),
        ),
    ]
