# Generated by Django 5.0.7 on 2024-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0002_artifactisdomain_times_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailheader',
            name='times_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
