# Generated by Django 5.1.6 on 2025-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0003_mailheader_times_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailartifact',
            name='artifact_level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailartifact',
            name='artifact_score',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='att_hash_level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='att_hash_score',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='attachment_level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='attachment_score',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='mailbody',
            name='body_level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailbody',
            name='body_score',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='mailheader',
            name='header_level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailheader',
            name='header_score',
            field=models.FloatField(default=5),
        ),
    ]
