# Generated by Django 5.1.7 on 2025-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_process', '0001_initial'),
        ('email_process', '0001_initial'),
        ('hash_process', '0002_alter_hash_ioc_level_alter_hash_ioc_score'),
        ('ip_process', '0002_alter_ip_ioc_level_alter_ip_ioc_score'),
        ('mail_feeder', '0004_alter_mailartifact_artifact_level_and_more'),
        ('url_process', '0003_alter_url_ioc_level_alter_url_ioc_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifactisdomain',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='artifactishash',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='artifactisip',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='artifactismailaddress',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='artifactisurl',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='mailanalyzed',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='mailartifact',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='mailattachment',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='mailbody',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='mailheader',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='mailinfo',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='artifactisdomain',
            name='associated_mails',
            field=models.ManyToManyField(blank=True, to='mail_feeder.mail'),
        ),
        migrations.AlterField(
            model_name='artifactisdomain',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='artifactisdomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artifactishash',
            name='associated_mails',
            field=models.ManyToManyField(blank=True, to='mail_feeder.mail'),
        ),
        migrations.AlterField(
            model_name='artifactishash',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='artifactishash',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artifactisip',
            name='associated_mails',
            field=models.ManyToManyField(blank=True, to='mail_feeder.mail'),
        ),
        migrations.AlterField(
            model_name='artifactisip',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='artifactisip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artifactismailaddress',
            name='associated_mails',
            field=models.ManyToManyField(blank=True, to='mail_feeder.mail'),
        ),
        migrations.AlterField(
            model_name='artifactismailaddress',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='artifactismailaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artifactisurl',
            name='associated_mails',
            field=models.ManyToManyField(blank=True, to='mail_feeder.mail'),
        ),
        migrations.AlterField(
            model_name='artifactisurl',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='artifactisurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_artifacts',
            field=models.ManyToManyField(blank=True, to='mail_feeder.mailartifact'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_attachments',
            field=models.ManyToManyField(blank=True, to='mail_feeder.mailattachment'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mail',
            name='reportedBy',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mail',
            name='to',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mailanalyzed',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailanalyzed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailartifact',
            name='artifact_type',
            field=models.CharField(choices=[('URL', 'URL'), ('IP', 'IP'), ('Hash', 'Hash'), ('Domain', 'Domain'), ('MailAddress', 'MailAddress')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mailartifact',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailartifact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailbody',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailbody',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailbody',
            name='other_values',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mailheader',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailheader',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailheader',
            name='other_values',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='artifactisdomain',
            index=models.Index(fields=['times_sent'], name='mail_feeder_times_s_881562_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactishash',
            index=models.Index(fields=['times_sent'], name='mail_feeder_times_s_c610dd_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactisip',
            index=models.Index(fields=['times_sent'], name='mail_feeder_times_s_c73095_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactismailaddress',
            index=models.Index(fields=['times_sent'], name='mail_feeder_times_s_45850b_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactisurl',
            index=models.Index(fields=['times_sent'], name='mail_feeder_times_s_5c138c_idx'),
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['mail_id'], name='mail_feeder_mail_id_b73893_idx'),
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['date'], name='mail_feeder_date_871199_idx'),
        ),
        migrations.AddIndex(
            model_name='mailartifact',
            index=models.Index(fields=['artifact_type'], name='mail_feeder_artifac_f1787e_idx'),
        ),
        migrations.AddIndex(
            model_name='mailbody',
            index=models.Index(fields=['fuzzy_hash'], name='mail_feeder_fuzzy_h_dfe882_idx'),
        ),
        migrations.AddIndex(
            model_name='mailheader',
            index=models.Index(fields=['fuzzy_hash'], name='mail_feeder_fuzzy_h_eeda80_idx'),
        ),
    ]
