# Generated by Django 5.2.1 on 2025-05-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0005_alter_artifactisdomain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='bcc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_from',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
