# Generated by Django 5.2.1 on 2025-05-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_process', '0002_alter_file_file_level_alter_file_file_score'),
        ('mail_feeder', '0006_mail_bcc_mail_mail_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_archive', to='file_process.file')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_archive', to='mail_feeder.mail')),
            ],
        ),
    ]
