# Generated by Django 5.2.4 on 2025-07-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0007_mailarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactisdomain',
            name='associated_mails',
        ),
        migrations.RemoveField(
            model_name='artifactishash',
            name='associated_mails',
        ),
        migrations.RemoveField(
            model_name='artifactisip',
            name='associated_mails',
        ),
        migrations.RemoveField(
            model_name='artifactismailaddress',
            name='associated_mails',
        ),
        migrations.RemoveField(
            model_name='artifactisurl',
            name='associated_mails',
        ),
        migrations.AddField(
            model_name='mailartifact',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_artifacts_new', to='mail_feeder.mail'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_attachments_new', to='mail_feeder.mail'),
        ),
    ]
