# Generated by Django 5.2.4 on 2025-07-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0008_remove_artifactisdomain_associated_mails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailartifact',
            old_name='test',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='mailattachment',
            old_name='test',
            new_name='mail',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='mail_artifacts',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='mail_attachments',
        ),
    ]
