# Generated by Django 5.2.5 on 2025-08-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0009_rename_test_mailartifact_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailartifact',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_artifacts', to='mail_feeder.mail'),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_attachments', to='mail_feeder.mail'),
        ),
    ]
