# Generated by Django 5.2.10 on 2026-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0010_alter_mailartifact_mail_alter_mailattachment_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailarchive',
            name='bucket_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
