# Generated by Django 5.2.10 on 2026-02-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0011_mailarchive_bucket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='preview_png',
            field=models.ImageField(blank=True, null=True, upload_to='mail_previews/'),
        ),
    ]
