# Generated by Django 5.2.12 on 2026-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0012_mail_preview_png'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='minio_object_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='mail',
            name='minio_submission_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
