# Generated by Django 6.0.4 on 2026-05-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0013_mail_minio_object_key_mail_minio_submission_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mail',
            name='mail_feeder_mail_id_b73893_idx',
        ),
        migrations.RemoveIndex(
            model_name='mail',
            name='mail_feeder_date_871199_idx',
        ),
        migrations.RemoveIndex(
            model_name='mailartifact',
            name='mail_feeder_artifac_f1787e_idx',
        ),
    ]
