# Generated by Django 6.0.4 on 2026-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0014_remove_mail_mail_feeder_mail_id_b73893_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mailbody',
            name='mail_feeder_fuzzy_h_dfe882_idx',
        ),
        migrations.RemoveIndex(
            model_name='mailheader',
            name='mail_feeder_fuzzy_h_eeda80_idx',
        ),
        migrations.AlterField(
            model_name='mailbody',
            name='fuzzy_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='mailheader',
            name='fuzzy_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
