# Generated by Django 6.0.5 on 2026-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0016_mail_preview_minio_explicit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='preview_object_key',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
    ]
