# Generated by Django 6.0.4 on 2026-06-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0017_alter_mail_preview_object_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbody',
            name='other_values',
        ),
        migrations.RemoveField(
            model_name='mailheader',
            name='other_values',
        ),
    ]
