# Generated by Django 6.0.5 on 2026-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0018_remove_mailbody_other_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='reporterNote',
            field=models.TextField(blank=True, default=''),
        ),
    ]
