# Generated by Django 6.1.1 on 2026-10-07 14:14

from django.db import migrations

from common.migration_utils import refuse_if_rows


class Migration(migrations.Migration):

    dependencies = [
        ('mail_feeder', '0021_remove_mail_minio_object_key'),
    ]

    operations = [
        refuse_if_rows('mail_feeder', 'MailAnalyzed'),
        migrations.DeleteModel(
            name='MailAnalyzed',
        ),
    ]
