# Generated by Django 5.2.12 on 2026-03-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(db_index=True, help_text="Globally unique ID for this submission. Matches the MinIO subdirectory name, e.g. '251215150557-388c4d591d6f'.", max_length=255, unique=True)),
                ('bucket_name', models.CharField(db_index=True, help_text='Source MinIO bucket name.', max_length=255)),
                ('minio_prefix', models.CharField(help_text="Object key prefix for all objects belonging to this submission, e.g. 'submissions/2025/12/251215150557-388c4d591d6f/'.", max_length=512)),
                ('minio_manifest_key', models.CharField(blank=True, help_text="Full object key for the metadata.json manifest, e.g. 'submissions/2025/12/251215150557-388c4d591d6f/metadata.json'. Empty if the submission predates manifest support.", max_length=512)),
                ('reported_by', models.EmailField(db_index=True, help_text='Email address of the reporter, extracted from metadata.json at ingest time. Eliminates the need to re-parse user_submission.eml.', max_length=254)),
                ('mail_id', models.IntegerField(blank=True, db_index=True, help_text='PK of the Mail row created during processing. Null until stage MAIL_PERSISTED.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('retry', 'Retry')], db_index=True, default='pending', max_length=20)),
                ('current_stage', models.CharField(blank=True, choices=[('fetched', 'Fetched from MinIO'), ('parsed', 'Email parsed'), ('mail_persisted', 'Mail + header + body persisted'), ('artifacts_extracted', 'Artifacts and attachments extracted'), ('case_created', 'Case created'), ('notified', 'User notified')], help_text='Last successfully completed processing stage. Used to resume processing without restarting from scratch.', max_length=40)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Number of retry attempts so far.')),
                ('retry_after', models.DateTimeField(blank=True, db_index=True, help_text='Earliest time this item should be retried. Null when not in retry state.', null=True)),
                ('error_detail', models.TextField(blank=True, help_text='Last error message or traceback excerpt. Overwritten on each attempt.')),
                ('worker_id', models.CharField(blank=True, help_text='Identifier of the worker that last claimed this item.', max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when the current worker claimed this item.', null=True)),
                ('submitted_at', models.DateTimeField(help_text='When the submission landed in MinIO (from metadata.json).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Submission queue item',
                'verbose_name_plural': 'Submission queue',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'retry_after'], name='submission__status_b8237e_idx'), models.Index(fields=['status', 'locked_at'], name='submission__status_b7edc3_idx'), models.Index(fields=['submission_id'], name='submission__submiss_3b25b8_idx'), models.Index(fields=['mail_id'], name='submission__mail_id_9625f2_idx')],
            },
        ),
    ]
