# Generated by Django 6.1.1 on 2026-10-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_queue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submissionqueue',
            name='submission__submiss_3b25b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='submissionqueue',
            name='submission__mail_id_9625f2_idx',
        ),
        migrations.AlterField(
            model_name='submissionqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissionqueue',
            name='submission_id',
            field=models.CharField(help_text="Globally unique ID for this submission. Matches the MinIO subdirectory name, e.g. '251215150557-388c4d591d6f'.", max_length=255, unique=True),
        ),
    ]
