# Generated by Django 6.1.1 on 2026-10-07 14:14

from django.db import migrations

from common.migration_utils import refuse_if_rows


class Migration(migrations.Migration):

    dependencies = [
        ('submission_queue', '0002_drop_redundant_indexes'),
    ]

    operations = [
        refuse_if_rows('submission_queue', 'SubmissionQueue'),
        migrations.RemoveIndex(
            model_name='submissionqueue',
            name='submission__status_b8237e_idx',
        ),
        migrations.RemoveIndex(
            model_name='submissionqueue',
            name='submission__status_b7edc3_idx',
        ),
        migrations.DeleteModel(
            name='SubmissionQueue',
        ),
    ]
