# Generated by Django 5.1 on 2024-08-22 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCasesSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suspicious_cases', models.PositiveIntegerField(default=0)),
                ('inconclusive_cases', models.PositiveIntegerField(default=0)),
                ('failure_cases', models.PositiveIntegerField(default=0)),
                ('dangerous_cases', models.PositiveIntegerField(default=0)),
                ('safe_cases', models.PositiveIntegerField(default=0)),
                ('challenged_cases', models.PositiveIntegerField(default=0)),
                ('whitelisted_cases', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReporterStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_reporters', models.PositiveIntegerField(default=0)),
                ('total_reporters', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCasesStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('monthly_cases_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='dashboard.monthlycasessummary')),
                ('monthly_reporter_stats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='dashboard.monthlyreporterstats')),
                ('total_cases_stats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='dashboard.totalcasesstats')),
            ],
        ),
        migrations.CreateModel(
            name='UserCasesMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspicious_cases', models.PositiveIntegerField(default=0)),
                ('inconclusive_cases', models.PositiveIntegerField(default=0)),
                ('failure_cases', models.PositiveIntegerField(default=0)),
                ('dangerous_cases', models.PositiveIntegerField(default=0)),
                ('safe_cases', models.PositiveIntegerField(default=0)),
                ('challenged_cases', models.PositiveIntegerField(default=0)),
                ('whitelisted_cases', models.PositiveIntegerField(default=0)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('month', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cases_monthly_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
