# Generated by Django 5.2.5 on 2025-08-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlycasessummary',
            old_name='whitelisted_cases',
            new_name='allow_listed_cases',
        ),
        migrations.RenameField(
            model_name='usercasesmonthlystats',
            old_name='whitelisted_cases',
            new_name='allow_listed_cases',
        ),
    ]
