# Generated by Django 5.2.9 on 2026-01-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_whitelisted_cases_monthlycasessummary_allow_listed_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycasessummary',
            name='blackmail_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlycasessummary',
            name='classic_phishing_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlycasessummary',
            name='clone_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlycasessummary',
            name='external_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlycasessummary',
            name='internal_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlycasessummary',
            name='newsletter_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlycasessummary',
            name='spam_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlycasessummary',
            name='uncategorized_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlycasessummary',
            name='whaling_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='blackmail_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='classic_phishing_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='clone_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='external_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='internal_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='newsletter_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='spam_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='uncategorized_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercasesmonthlystats',
            name='whaling_cases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
