# Generated by Django 5.2.12 on 2026-03-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_monthlycasessummary_blackmail_cases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('suspicious_cases', models.PositiveIntegerField(default=0)),
                ('inconclusive_cases', models.PositiveIntegerField(default=0)),
                ('failure_cases', models.PositiveIntegerField(default=0)),
                ('dangerous_cases', models.PositiveIntegerField(default=0)),
                ('safe_cases', models.PositiveIntegerField(default=0)),
                ('challenged_cases', models.PositiveIntegerField(default=0)),
                ('allow_listed_cases', models.PositiveIntegerField(default=0)),
                ('uncategorized_cases', models.PositiveIntegerField(default=0)),
                ('spam_cases', models.PositiveIntegerField(default=0)),
                ('newsletter_cases', models.PositiveIntegerField(default=0)),
                ('classic_phishing_cases', models.PositiveIntegerField(default=0)),
                ('clone_cases', models.PositiveIntegerField(default=0)),
                ('blackmail_cases', models.PositiveIntegerField(default=0)),
                ('whaling_cases', models.PositiveIntegerField(default=0)),
                ('internal_cases', models.PositiveIntegerField(default=0)),
                ('external_cases', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
