# Generated by Django 5.2.13 on 2026-04-29 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dashboardsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dashboardsnapshot',
            index=models.Index(fields=['year', 'month'], name='snapshot_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmonthlystats',
            index=models.Index(fields=['year', 'month'], name='gms_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmonthlystats',
            index=models.Index(fields=['year', 'month', 'group_name'], name='gms_ymg_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['year', 'month'], name='kpi_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycasessummary',
            index=models.Index(fields=['creation_date'], name='mcs_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreporterstats',
            index=models.Index(fields=['creation_date'], name='mrs_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='totalcasesstats',
            index=models.Index(fields=['creation_date'], name='tcs_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='usercasesmonthlystats',
            index=models.Index(fields=['year', 'month'], name='ucms_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='usercasesmonthlystats',
            index=models.Index(fields=['year', 'month', 'user'], name='ucms_ymu_idx'),
        ),
        migrations.AddIndex(
            model_name='usercasesmonthlystats',
            index=models.Index(fields=['user', 'year', 'month'], name='ucms_uym_idx'),
        ),
    ]
