# Generated by Django 6.0.5 on 2026-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dashboardsnapshot_snapshot_ym_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelRetrainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_timestamp', models.DateTimeField()),
                ('dataset_dir', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('f1_score', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('promoted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-run_timestamp'],
                'indexes': [models.Index(fields=['label', '-run_timestamp'], name='ai_run_label_ts_idx')],
            },
        ),
    ]
