# Generated by Django 6.1.1 on 2026-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_process', '0003_alter_ip_address_ipv6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='address',
            field=models.CharField(db_index=True, max_length=45),
        ),
    ]
