# Generated by Django 5.1 on 2024-08-22 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CISOProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=200)),
                ('gbu', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('scope', models.CharField(default='Not defined', max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=200)),
                ('gbu', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('wants_acknowledgement', models.BooleanField(default=True)),
                ('wants_results', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
