# Generated by Django 5.2.5 on 2025-08-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_cisoprofile_theme_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='cisoprofile',
            name='wants_acknowledgement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cisoprofile',
            name='wants_results',
            field=models.BooleanField(default=True),
        ),
    ]
