# Generated by Django 5.2.12 on 2026-03-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisoprofile',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('graphite', 'Graphite'), ('slate', 'Slate'), ('light', 'Light'), ('paper', 'Paper'), ('high_contrast', 'High contrast'), ('sunrise', 'Sunrise'), ('valentine', 'Valentine'), ('cyber', 'Cyber'), ('the_one', 'The One'), ('metal', 'Metal')], default='graphite', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('graphite', 'Graphite'), ('slate', 'Slate'), ('light', 'Light'), ('paper', 'Paper'), ('high_contrast', 'High contrast'), ('sunrise', 'Sunrise'), ('valentine', 'Valentine'), ('cyber', 'Cyber'), ('the_one', 'The One'), ('metal', 'Metal')], default='graphite', max_length=50),
        ),
    ]
