# Generated by Django 5.2.12 on 2026-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_cisoprofile_theme_alter_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='cisoprofile',
            name='auto_seasonal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_seasonal',
            field=models.BooleanField(default=True),
        ),
    ]
