# Generated by Django 5.2.12 on 2026-03-23 13:43

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_cisoprofile_theme_alter_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='cisoprofile',
            name='semantic_colors',
            field=models.JSONField(blank=True, default=profiles.models.CISOProfile.default_semantic_colors, help_text="User-defined colors for result/status indicators. Structure: {result: {safe, suspicious, dangerous, inconclusive}, status: {done, in_progress, new, failure, challenged, unknown}}. Each entry is {main: '#rrggbb'}.", verbose_name='Semantic colors'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semantic_colors',
            field=models.JSONField(blank=True, default=profiles.models.UserProfile.default_semantic_colors, help_text="User-defined colors for result/status indicators. Structure: {result: {safe, suspicious, dangerous, inconclusive}, status: {done, in_progress, new, failure, challenged, unknown}}. Each entry is {main: '#rrggbb'}.", verbose_name='Semantic colors'),
        ),
        migrations.AlterField(
            model_name='cisoprofile',
            name='auto_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cisoprofile',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('graphite', 'Graphite'), ('slate', 'Slate'), ('light', 'Light'), ('paper', 'Paper'), ('high_contrast', 'High contrast'), ('sunrise', 'Sunrise'), ('valentine', 'Valentine'), ('cyber', 'Cyber'), ('the_one', 'The One'), ('metal', 'Metal'), ('future', 'Future'), ('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn')], default='graphite', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auto_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('graphite', 'Graphite'), ('slate', 'Slate'), ('light', 'Light'), ('paper', 'Paper'), ('high_contrast', 'High contrast'), ('sunrise', 'Sunrise'), ('valentine', 'Valentine'), ('cyber', 'Cyber'), ('the_one', 'The One'), ('metal', 'Metal'), ('future', 'Future'), ('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn')], default='graphite', max_length=50),
        ),
    ]
