# Generated by Django 6.0.5 on 2026-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_cisoprofile_semantic_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisoprofile',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('graphite', 'Graphite'), ('slate', 'Slate'), ('light', 'Light'), ('paper', 'Paper'), ('high_contrast', 'High contrast'), ('sunrise', 'Sunrise'), ('valentine', 'Valentine'), ('cyber', 'Cyber'), ('the_one', 'The One'), ('metal', 'Metal'), ('future', 'Future'), ('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn')], default='light', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('graphite', 'Graphite'), ('slate', 'Slate'), ('light', 'Light'), ('paper', 'Paper'), ('high_contrast', 'High contrast'), ('sunrise', 'Sunrise'), ('valentine', 'Valentine'), ('cyber', 'Cyber'), ('the_one', 'The One'), ('metal', 'Metal'), ('future', 'Future'), ('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn')], default='light', max_length=50),
        ),
    ]
