# Generated by Django 6.0.7 on 2026-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_userprofile_tour_completed_cisoprofile_tour_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cisoprofile',
            name='sidebar_pinned',
            field=models.BooleanField(default=False, help_text='True if the user has pinned the navigation sidebar open.', verbose_name='Sidebar pinned'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_pinned',
            field=models.BooleanField(default=False, help_text='True if the user has pinned the navigation sidebar open.', verbose_name='Sidebar pinned'),
        ),
    ]
