services:
  greenmail:
    image: greenmail/standalone:latest
    container_name: greenmail
    ports:
      - "3025:3025" # SMTP
      - "3110:3110" # POP3
      - "3143:3143" # IMAP
      - "3465:3465" # SMTPS
      - "3995:3995" # POP3S
      - "3993:3993" # IMAPS
    environment:
      GREENMAIL_OPTS: >
        -Dgreenmail.setup.test.all
        -Dgreenmail.users=imap_user:imap_password@localhost
        -Dgreenmail.verbose
        -Dgreenmail.starttls.enable=false
        -Dgreenmail.hostname=0.0.0.0
    volumes:
      - greenmail_data:/data
    restart: unless-stopped

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    command: /data --console-address ":9001"
    restart: always
    expose:
      - "9000"
    ports:
      - "127.0.0.1:9001:9001"
    environment:
      RUSTFS_ACCESS_KEY:    ${MINIO_ROOT_USER}
      RUSTFS_SECRET_KEY:    ${MINIO_ROOT_PASSWORD}
      RUSTFS_VOLUMES:       /data
      RUSTFS_ADDRESS:       0.0.0.0:9000
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
    volumes:
      - "rustfs_data:/data:Z"

volumes:
  rustfs_data:
  greenmail_data:
