# Generated by Django 5.2.5 on 2025-08-20 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_process', '0002_domain_ioc_confidence_domain_ioc_level_and_more'),
        ('hash_process', '0002_alter_hash_ioc_level_alter_hash_ioc_score'),
        ('settings', '0004_campaigndomainwhitelist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhitelistFiletype',
            new_name='AllowListFiletype',
        ),
        migrations.RemoveField(
            model_name='blacklistfile',
            name='linked_file_hash',
        ),
        migrations.RemoveField(
            model_name='blacklistfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='campaigndomainwhitelist',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='campaigndomainwhitelist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='whitelistdomain',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='whitelistdomain',
            name='user',
        ),
        migrations.RemoveField(
            model_name='whitelistfile',
            name='linked_file_hash',
        ),
        migrations.RemoveField(
            model_name='whitelistfile',
            name='user',
        ),
        migrations.CreateModel(
            name='AllowListDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allow_lists', to='domain_process.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllowListFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('linked_file_hash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allow_lists', to='hash_process.hash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDomainAllowList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_allow_lists', to='domain_process.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DenyListDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deny_lists', to='domain_process.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DenyListFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('linked_file_hash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deny_lists', to='hash_process.hash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BlacklistDomain',
        ),
        migrations.DeleteModel(
            name='BlacklistFile',
        ),
        migrations.DeleteModel(
            name='CampaignDomainWhitelist',
        ),
        migrations.DeleteModel(
            name='WhitelistDomain',
        ),
        migrations.DeleteModel(
            name='WhitelistFile',
        ),
    ]
