# Generated by Django 5.2.12 on 2026-03-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_process', '0002_domain_ioc_confidence_domain_ioc_level_and_more'),
        ('settings', '0005_rename_whitelistfiletype_allowlistfiletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatcherLegitDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watcher_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('remote_last_update', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legit_lists', to='domain_process.domain')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('domain',), name='uniq_watcher_legit_domain')],
            },
        ),
        migrations.CreateModel(
            name='WatcherMonitoredDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watcher_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('remote_last_update', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitored_lists', to='domain_process.domain')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('domain',), name='uniq_watcher_monitored_domain')],
            },
        ),
    ]
