# Generated by Django 6.0.4 on 2026-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_runtimeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='scope',
            field=models.CharField(choices=[('shared', 'shared'), ('backend', 'backend'), ('feeder', 'feeder')], default='backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='runtimeconfig',
            name='key',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='runtimeconfig',
            constraint=models.UniqueConstraint(fields=('scope', 'key'), name='uniq_scope_key'),
        ),
    ]
