# Generated by Django 6.1.1 on 2026-10-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_allowlistip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailbox',
        ),
    ]
