# Generated by Django 6.1.1 on 2026-10-07 14:14

from django.db import migrations

from common.migration_utils import refuse_if_rows


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_delete_mailbox'),
    ]

    operations = [
        refuse_if_rows('settings', 'DenyListFile'),
        migrations.DeleteModel(
            name='DenyListFile',
        ),
    ]
