# Generated by Django 6.1.1 on 2026-10-08 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_process', '0003_domain_value_prefix_index'),
        ('hash_process', '0003_lookup_indexes'),
        ('ip_process', '0004_lookup_indexes'),
        ('settings', '0011_delete_denylistfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='allowlistdomain',
            constraint=models.UniqueConstraint(fields=('domain',), name='uniq_allowlistdomain_domain'),
        ),
        migrations.AddConstraint(
            model_name='allowlistfile',
            constraint=models.UniqueConstraint(fields=('linked_file_hash',), name='uniq_allowlistfile_hash'),
        ),
        migrations.AddConstraint(
            model_name='allowlistip',
            constraint=models.UniqueConstraint(fields=('ip',), name='uniq_allowlistip_ip'),
        ),
        migrations.AddConstraint(
            model_name='campaigndomainallowlist',
            constraint=models.UniqueConstraint(fields=('domain',), name='uniq_campaigndomainallowlist_domain'),
        ),
        migrations.AddConstraint(
            model_name='denylistdomain',
            constraint=models.UniqueConstraint(fields=('domain',), name='uniq_denylistdomain_domain'),
        ),
    ]
