apiVersion: v1
kind: Service
metadata:
  name: {{ include "suspicious.fullname" . }}
  labels:
    {{- include "suspicious.labels" . | nindent 4 }}
    app.kubernetes.io/component: suspicious
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: suspicious
  ports:
    - port: {{ .Values.suspicious.service.port }}
      targetPort: 9020
