# Generated by Django 5.1 on 2024-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('ioc_score', models.FloatField(default=0)),
                ('ioc_confidence', models.FloatField(default=0)),
                ('ioc_level', models.CharField(default='unknown level', max_length=20)),
                ('hashtype', models.CharField(default='sha256 hash', max_length=50)),
                ('times_sent', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
