# Generated by Django 5.1.6 on 2025-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='ioc_level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='hash',
            name='ioc_score',
            field=models.FloatField(default=5),
        ),
    ]
