# Generated by Django 6.1.1 on 2026-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_process', '0002_alter_hash_ioc_level_alter_hash_ioc_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='value',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
