# Generated by Django 5.1 on 2024-08-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_process', '__first__'),
        ('hash_process', '__first__'),
        ('ip_process', '__first__'),
        ('mail_feeder', '__first__'),
        ('url_process', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weight', models.FloatField()),
                ('analyzer_cortex_id', models.CharField(max_length=50, unique=True)),
                ('analyzer_cortex_2_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzerReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cortex_job_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('score', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('report_summary', models.JSONField()),
                ('report_taxonomy', models.JSONField()),
                ('report_full', models.JSONField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='cortex_job.analyzer')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='file_process.file')),
                ('hash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='hash_process.hash')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='ip_process.ip')),
                ('mail_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='mail_feeder.mailbody')),
                ('mail_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='mail_feeder.mailheader')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='url_process.url')),
            ],
        ),
    ]
