# Generated by Django 5.1.7 on 2025-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzerreport',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
