# Generated by Django 5.1.7 on 2025-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0002_alter_analyzerreport_category'),
        ('file_process', '0002_alter_file_file_level_alter_file_file_score'),
        ('hash_process', '0002_alter_hash_ioc_level_alter_hash_ioc_score'),
        ('ip_process', '0002_alter_ip_ioc_level_alter_ip_ioc_score'),
        ('mail_feeder', '0004_alter_mailartifact_artifact_level_and_more'),
        ('url_process', '0003_alter_url_ioc_level_alter_url_ioc_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzer',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='analyzerreport',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='analyzer',
            name='analyzer_cortex_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='analyzer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='analyzer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='analyzer',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='analyzerreport',
            name='cortex_job_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='analyzerreport',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='analyzerreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='analyzerreport',
            name='level',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='analyzerreport',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='analyzerreport',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='analyzer',
            index=models.Index(fields=['analyzer_cortex_id'], name='cortex_job__analyze_8fc50e_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['cortex_job_id'], name='cortex_job__cortex__2b1d25_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type'], name='cortex_job__type_e0b62a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['status'], name='cortex_job__status_feb548_idx'),
        ),
    ]
