# Generated by Django 5.1.7 on 2025-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0003_alter_analyzer_options_alter_analyzerreport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzer',
            name='analyzer_cortex_2_id',
        ),
        migrations.AlterField(
            model_name='analyzer',
            name='weight',
            field=models.FloatField(default=0.2),
        ),
    ]
