# Generated by Django 5.2.1 on 2025-05-31 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0004_remove_analyzer_analyzer_cortex_2_id_and_more'),
        ('domain_process', '0002_domain_ioc_confidence_domain_ioc_level_and_more'),
        ('email_process', '0002_mailaddress_ioc_confidence_mailaddress_ioc_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerreport',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='domain_process.domain'),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_reports', to='email_process.mailaddress'),
        ),
    ]
