# Generated by Django 6.0.4 on 2026-05-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0005_analyzerreport_domain_analyzerreport_mail'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analyzer',
            name='cortex_job__analyze_8fc50e_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyzerreport',
            name='cortex_job__cortex__2b1d25_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyzerreport',
            name='cortex_job__type_e0b62a_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyzerreport',
            name='cortex_job__status_feb548_idx',
        ),
    ]
