# Generated by Django 6.0.4 on 2026-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0006_remove_analyzer_cortex_job__analyze_8fc50e_idx_and_more'),
        ('domain_process', '0002_domain_ioc_confidence_domain_ioc_level_and_more'),
        ('email_process', '0002_mailaddress_ioc_confidence_mailaddress_ioc_level_and_more'),
        ('file_process', '0002_alter_file_file_level_alter_file_file_score'),
        ('hash_process', '0002_alter_hash_ioc_level_alter_hash_ioc_score'),
        ('ip_process', '0002_alter_ip_ioc_level_alter_ip_ioc_score'),
        ('mail_feeder', '0015_remove_mailbody_mail_feeder_fuzzy_h_dfe882_idx_and_more'),
        ('url_process', '0003_alter_url_ioc_level_alter_url_ioc_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type', 'status', 'domain'], name='cortex_job__type_aad087_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type', 'status', 'url'], name='cortex_job__type_b6b12f_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type', 'status', 'ip'], name='cortex_job__type_4a0ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type', 'status', 'hash'], name='cortex_job__type_bdd9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type', 'status', 'mail'], name='cortex_job__type_a7d014_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type', 'status', 'file'], name='cortex_job__type_275ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type', 'status', 'mail_body'], name='cortex_job__type_e4e3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerreport',
            index=models.Index(fields=['type', 'status', 'mail_header'], name='cortex_job__type_a2ee10_idx'),
        ),
    ]
