# Generated by Django 6.0.4 on 2026-05-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0013_drop_caseartifact_partial_constraints'),
        ('cortex_job', '0007_analyzerreport_cortex_job__type_aad087_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalyzerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortex_job_id', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('InProgress', 'InProgress'), ('Success', 'Success'), ('Failure', 'Failure'), ('Deleted', 'Deleted')], default='InProgress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_jobs', to='cortex_job.analyzer')),
                ('analyzer_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_jobs', to='cortex_job.analyzerreport')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_jobs', to='case_handler.case')),
            ],
            options={
                'indexes': [models.Index(fields=['cortex_job_id'], name='cortex_job__cortex__c33b96_idx'), models.Index(fields=['case', 'status'], name='cortex_job__case_id_5eafbb_idx'), models.Index(fields=['status', 'created_at'], name='cortex_job__status_ca3588_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'cortex_job_id'), name='uniq_case_cortexjob')],
            },
        ),
    ]
