# Generated by Django 6.0.4 on 2026-05-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0008_caseanalyzerjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseanalyzerjob',
            name='cortex_job_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='caseanalyzerjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
