# Generated by Django 6.0.7 on 2026-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0010_backfill_caseanalyzerjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzer',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Authoritative'), (2, 'Strong'), (3, 'Contextual')], db_index=True, default=3, help_text='Fixed trust classification. 1 = authoritative source, 3 = contextual/noisy.'),
        ),
    ]
