# Generated by Django 6.0.7 on 2026-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0012_seed_analyzer_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerreport',
            name='enrichment',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
