# Generated by Django 6.1 on 2026-09-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_handler', '0027_case_observable_group'),
        ('cortex_job', '0013_analyzerreport_enrichment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedObservable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_analyzer', models.CharField(max_length=64)),
                ('parent_type', models.CharField(max_length=16)),
                ('parent_id', models.PositiveIntegerField()),
                ('child_type', models.CharField(max_length=16)),
                ('child_id', models.PositiveIntegerField()),
                ('child_value', models.CharField(max_length=512)),
                ('child_band', models.CharField(blank=True, default='', max_length=16)),
                ('escalation_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_observables', to='case_handler.case')),
                ('source_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_observables', to='cortex_job.analyzerreport')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'parent_type', 'parent_id'], name='cortex_job__case_id_d78519_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_report', 'child_type', 'child_id'), name='uniq_derived_per_report_child')],
            },
        ),
    ]
