# Generated by Django 6.1 on 2026-09-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0014_derivedobservable'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerreport',
            name='screenshot_bucket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analyzerreport',
            name='screenshot_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
    ]
