# Generated by Django 6.1.1 on 2026-10-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex_job', '0015_analyzerreport_screenshot'),
        ('domain_process', '0003_domain_value_prefix_index'),
        ('email_process', '0003_mailaddress_address_prefix_index'),
        ('file_process', '0002_alter_file_file_level_alter_file_file_score'),
        ('hash_process', '0003_lookup_indexes'),
        ('ip_process', '0004_lookup_indexes'),
        ('mail_feeder', '0022_delete_mailanalyzed'),
        ('url_process', '0005_url_address_prefix_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analyzerreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('url__isnull', False), ('domain__isnull', True), ('mail__isnull', True), ('hash__isnull', True), ('file__isnull', True), ('ip__isnull', True), ('mail_body__isnull', True), ('mail_header__isnull', True)), models.Q(('domain__isnull', False), ('url__isnull', True), ('mail__isnull', True), ('hash__isnull', True), ('file__isnull', True), ('ip__isnull', True), ('mail_body__isnull', True), ('mail_header__isnull', True)), models.Q(('mail__isnull', False), ('url__isnull', True), ('domain__isnull', True), ('hash__isnull', True), ('file__isnull', True), ('ip__isnull', True), ('mail_body__isnull', True), ('mail_header__isnull', True)), models.Q(('hash__isnull', False), ('url__isnull', True), ('domain__isnull', True), ('mail__isnull', True), ('file__isnull', True), ('ip__isnull', True), ('mail_body__isnull', True), ('mail_header__isnull', True)), models.Q(('file__isnull', False), ('url__isnull', True), ('domain__isnull', True), ('mail__isnull', True), ('hash__isnull', True), ('ip__isnull', True), ('mail_body__isnull', True), ('mail_header__isnull', True)), models.Q(('ip__isnull', False), ('url__isnull', True), ('domain__isnull', True), ('mail__isnull', True), ('hash__isnull', True), ('file__isnull', True), ('mail_body__isnull', True), ('mail_header__isnull', True)), models.Q(('mail_body__isnull', False), ('url__isnull', True), ('domain__isnull', True), ('mail__isnull', True), ('hash__isnull', True), ('file__isnull', True), ('ip__isnull', True), ('mail_header__isnull', True)), models.Q(('mail_header__isnull', False), ('url__isnull', True), ('domain__isnull', True), ('mail__isnull', True), ('hash__isnull', True), ('file__isnull', True), ('ip__isnull', True), ('mail_body__isnull', True)), _connector='OR'), name='analyzerreport_one_target_chk'),
        ),
    ]
